package configsettings

func AgentFields() []Field {
	zero := 0.0
	one := 1.0
	return []Field{
		{Path: "llm.inference_provider", Kind: KindString, ApplyMode: ApplyNextGeneration},
		{Path: "llm.provider", Kind: KindString, ApplyMode: ApplyNextGeneration},
		{Path: "llm.endpoint", Kind: KindString, ApplyMode: ApplyNextGeneration},
		{Path: "llm.model", Kind: KindString, ApplyMode: ApplyNextGeneration},
		{Path: "llm.context_window_tokens", Kind: KindInt, ApplyMode: ApplyNextGeneration, Min: &zero},
		{Path: "llm.api_key", Kind: KindString, Sensitive: true, ApplyMode: ApplyNextGeneration},
		{Path: "llm.headers", Kind: KindStringMap, ApplyMode: ApplyNextGeneration, Default: map[string]string{}},
		{Path: "llm.cache_ttl", Kind: KindString, ApplyMode: ApplyNextGeneration},
		{Path: "llm.cache_key_prefix", Kind: KindString, ApplyMode: ApplyNextGeneration},
		{Path: "llm.request_timeout", Kind: KindDuration, ApplyMode: ApplyNextGeneration},
		{Path: "llm.temperature", Kind: KindFloat, ApplyMode: ApplyNextGeneration},
		{Path: "llm.reasoning_effort", Kind: KindString, ApplyMode: ApplyNextGeneration, Enum: []string{"", "none", "minimal", "low", "medium", "high", "max", "xhigh"}},
		{Path: "llm.reasoning_budget_tokens", Kind: KindInt, ApplyMode: ApplyNextGeneration, Min: &zero},
		{Path: "llm.pricing_file", Kind: KindString, ApplyMode: ApplyNextGeneration},
		{Path: "llm.tools_emulation_mode", Kind: KindString, ApplyMode: ApplyNextGeneration, Enum: []string{"off", "fallback", "force"}},
		{Path: "llm.azure.deployment", Kind: KindString, ApplyMode: ApplyNextGeneration},
		{Path: "llm.bedrock.aws_key", Kind: KindString, Sensitive: true, ApplyMode: ApplyNextGeneration},
		{Path: "llm.bedrock.aws_secret", Kind: KindString, Sensitive: true, ApplyMode: ApplyNextGeneration},
		{Path: "llm.bedrock.aws_session_token", Kind: KindString, Sensitive: true, ApplyMode: ApplyNextGeneration},
		{Path: "llm.bedrock.aws_profile", Kind: KindString, ApplyMode: ApplyNextGeneration},
		{Path: "llm.bedrock.region", Kind: KindString, ApplyMode: ApplyNextGeneration},
		{Path: "llm.bedrock.model_arn", Kind: KindString, ApplyMode: ApplyNextGeneration},
		{Path: "llm.cloudflare.account_id", Kind: KindString, ApplyMode: ApplyNextGeneration},
		{Path: "llm.cloudflare.api_token", Kind: KindString, Sensitive: true, ApplyMode: ApplyNextGeneration},
		{Path: "llm.image.provider", Kind: KindString, ApplyMode: ApplyNextGeneration},
		{Path: "llm.image.endpoint", Kind: KindString, ApplyMode: ApplyNextGeneration},
		{Path: "llm.image.api_key", Kind: KindString, Sensitive: true, ApplyMode: ApplyNextGeneration},
		{Path: "llm.image.model", Kind: KindString, ApplyMode: ApplyNextGeneration},
		{Path: "llm.image.request_timeout", Kind: KindDuration, ApplyMode: ApplyNextGeneration},
		{Path: "llm.image.options.openai", Kind: KindJSON, ApplyMode: ApplyNextGeneration, Default: map[string]any{}},
		{Path: "llm.image.options.gemini", Kind: KindJSON, ApplyMode: ApplyNextGeneration, Default: map[string]any{}},
		{Path: "llm.image.options.cloudflare", Kind: KindJSON, ApplyMode: ApplyNextGeneration, Default: map[string]any{}},
		{Path: "llm.routes.main_loop", Kind: KindJSON, ApplyMode: ApplyNextGeneration, Default: map[string]any{}},
		{Path: "llm.routes.decision", Kind: KindJSON, ApplyMode: ApplyNextGeneration, Default: map[string]any{}},
		{Path: "llm.routes.addressing", Kind: KindJSON, ApplyMode: ApplyNextGeneration, Default: map[string]any{}},
		{Path: "llm.routes.awareness", Kind: KindJSON, ApplyMode: ApplyNextGeneration, Default: map[string]any{}},
		{Path: "llm.routes.think", Kind: KindJSON, ApplyMode: ApplyNextGeneration, Default: map[string]any{}},
		{Path: "llm.routes.plan_create", Kind: KindJSON, ApplyMode: ApplyNextGeneration, Default: map[string]any{}},

		{Path: "max_steps", Kind: KindInt, ApplyMode: ApplyNextGeneration, Min: &one},
		{Path: "parse_retries", Kind: KindInt, ApplyMode: ApplyNextGeneration, Min: &zero},
		{Path: "max_token_budget", Kind: KindInt, ApplyMode: ApplyNextGeneration, Min: &zero},
		{Path: "tool_repeat_limit", Kind: KindInt, ApplyMode: ApplyNextGeneration, Min: &one},
		{Path: "timeout", Kind: KindDuration, ApplyMode: ApplyNextGeneration},
		{Path: "context_compaction.enabled", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "context_compaction.trigger_ratio", Kind: KindFloat, ApplyMode: ApplyNextGeneration, Min: &zero, Max: &one},
		{Path: "tools.read_file.max_bytes", Kind: KindInt, ApplyMode: ApplyNextGeneration, Min: &zero},
		{Path: "tools.read_file.deny_paths", Kind: KindStringList, ApplyMode: ApplyNextGeneration},
		{Path: "tools.write_file.enabled", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "tools.write_file.max_bytes", Kind: KindInt, ApplyMode: ApplyNextGeneration, Min: &zero},
		{Path: "tools.spawn.enabled", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "tools.coder.enabled", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "tools.coder.path_extra", Kind: KindStringList, ApplyMode: ApplyNextGeneration},
		{Path: "tools.acp_spawn.enabled", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "tools.contacts_send.enabled", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "tools.todo_update.enabled", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "tools.plan_create.enabled", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "tools.plan_create.max_steps", Kind: KindInt, ApplyMode: ApplyNextGeneration, Min: &one},
		{Path: "tools.image_generate.enabled", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "tools.image_edit.enabled", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "tools.skill_install_preview.enabled", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "tools.skill_install.enabled", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "tools.skill_install.max_bytes", Kind: KindInt, ApplyMode: ApplyNextGeneration, Min: &zero},
		{Path: "tools.url_fetch.enabled", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "tools.url_fetch.timeout", Kind: KindDuration, ApplyMode: ApplyNextGeneration},
		{Path: "tools.url_fetch.max_bytes", Kind: KindInt, ApplyMode: ApplyNextGeneration, Min: &zero},
		{Path: "tools.url_fetch.max_bytes_download", Kind: KindInt, ApplyMode: ApplyNextGeneration, Min: &zero},
		{Path: "tools.web_search.enabled", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "tools.web_search.base_url", Kind: KindString, ApplyMode: ApplyNextGeneration},
		{Path: "tools.web_search.timeout", Kind: KindDuration, ApplyMode: ApplyNextGeneration},
		{Path: "tools.web_search.max_results", Kind: KindInt, ApplyMode: ApplyNextGeneration, Min: &one},
		{Path: "tools.bash.enabled", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "tools.bash.timeout", Kind: KindDuration, ApplyMode: ApplyNextGeneration},
		{Path: "tools.bash.max_output_bytes", Kind: KindInt, ApplyMode: ApplyNextGeneration, Min: &zero},
		{Path: "tools.bash.deny_paths", Kind: KindStringList, ApplyMode: ApplyNextGeneration},
		{Path: "tools.bash.path_extra", Kind: KindStringList, ApplyMode: ApplyNextGeneration},
		{Path: "tools.bash.injected_env_vars", Kind: KindJSON, ApplyMode: ApplyNextGeneration, Default: []any{}},
		{Path: "tools.bash.rewrite.enabled", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "tools.bash.rewrite.binary", Kind: KindString, ApplyMode: ApplyNextGeneration},
		{Path: "tools.powershell.enabled", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "tools.powershell.timeout", Kind: KindDuration, ApplyMode: ApplyNextGeneration},
		{Path: "tools.powershell.max_output_bytes", Kind: KindInt, ApplyMode: ApplyNextGeneration, Min: &zero},
		{Path: "tools.powershell.deny_paths", Kind: KindStringList, ApplyMode: ApplyNextGeneration},
		{Path: "tools.powershell.injected_env_vars", Kind: KindJSON, ApplyMode: ApplyNextGeneration, Default: []any{}},

		{Path: "skills.enabled", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "skills.load", Kind: KindStringList, ApplyMode: ApplyNextGeneration},
		{Path: "skills.dir_name", Kind: KindString, ApplyMode: ApplyRuntimeRestart},
		{Path: "mcp.servers", Kind: KindJSON, ApplyMode: ApplyNextGeneration, Default: []any{}},
		{Path: "acp.agents", Kind: KindJSON, ApplyMode: ApplyNextGeneration, Default: []any{}},
	}
}

func ConsoleFields() []Field {
	zero := 0.0
	one := 1.0
	fields := []Field{
		{Path: "console.listen", Kind: KindString, ApplyMode: ApplyProcessRestart},
		{Path: "console.base_path", Kind: KindString, ApplyMode: ApplyProcessRestart},
		{Path: "console.static_dir", Kind: KindString, ApplyMode: ApplyProcessRestart},
		{Path: "console.password", Kind: KindString, Sensitive: true, ApplyMode: ApplyProcessRestart},
		{Path: "console.password_hash", Kind: KindString, Sensitive: true, ApplyMode: ApplyProcessRestart},
		{Path: "console.session_ttl", Kind: KindDuration, ApplyMode: ApplyProcessRestart},
		{Path: "console.managed_runtimes", Kind: KindStringList, ApplyMode: ApplyRuntimeRestart},
		{Path: "server.auth_token", Kind: KindString, Sensitive: true, ApplyMode: ApplyRuntimeRestart},

		{Path: "heartbeat.enabled", Kind: KindBool, ApplyMode: ApplyRuntimeRestart},
		{Path: "heartbeat.interval", Kind: KindDuration, ApplyMode: ApplyRuntimeRestart},
		{Path: "cron.enabled", Kind: KindBool, ApplyMode: ApplyRuntimeRestart},

		{Path: "guard.enabled", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "guard.dir_name", Kind: KindString, ApplyMode: ApplyRuntimeRestart},
		{Path: "guard.network.url_fetch.allowed_url_prefixes", Kind: KindStringList, ApplyMode: ApplyNextGeneration},
		{Path: "guard.network.url_fetch.deny_private_ips", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "guard.network.url_fetch.follow_redirects", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "guard.network.url_fetch.allow_proxy", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "guard.redaction.enabled", Kind: KindBool, ApplyMode: ApplyNextGeneration},
		{Path: "guard.redaction.patterns", Kind: KindJSON, ApplyMode: ApplyNextGeneration, Default: []any{}},
		{Path: "guard.audit.jsonl_path", Kind: KindString, ApplyMode: ApplyRuntimeRestart},
		{Path: "guard.audit.rotate_max_bytes", Kind: KindInt, ApplyMode: ApplyRuntimeRestart, Min: &zero},
		{Path: "guard.approvals.enabled", Kind: KindBool, ApplyMode: ApplyNextGeneration},

		{Path: "admins", Kind: KindStringList, ApplyMode: ApplyRuntimeRestart},
		{Path: "secrets.allow_profiles", Kind: KindStringList, ApplyMode: ApplyNextGeneration},
		{Path: "secrets.aws_secrets_manager.region", Kind: KindString, ApplyMode: ApplyNextGeneration},
		{Path: "secrets.aws_secrets_manager.profile", Kind: KindString, ApplyMode: ApplyNextGeneration},
	}

	groupTrigger := []string{"smart", "strict", "talkative"}
	for _, channel := range []string{"telegram", "slack", "line", "lark"} {
		fields = append(fields,
			Field{Path: channel + ".group_trigger_mode", Kind: KindString, ApplyMode: ApplyRuntimeRestart, Enum: groupTrigger},
			Field{Path: channel + ".record_untriggered", Kind: KindBool, ApplyMode: ApplyRuntimeRestart},
			Field{Path: channel + ".addressing_confidence_threshold", Kind: KindFloat, ApplyMode: ApplyRuntimeRestart, Min: &zero, Max: &one},
			Field{Path: channel + ".addressing_interject_threshold", Kind: KindFloat, ApplyMode: ApplyRuntimeRestart, Min: &zero, Max: &one},
			Field{Path: channel + ".task_timeout", Kind: KindDuration, ApplyMode: ApplyRuntimeRestart},
			Field{Path: channel + ".max_concurrency", Kind: KindInt, ApplyMode: ApplyRuntimeRestart, Min: &one},
			Field{Path: channel + ".serve_listen", Kind: KindString, ApplyMode: ApplyProcessRestart},
		)
	}
	fields = append(fields,
		Field{Path: "telegram.bot_token", Kind: KindString, Sensitive: true, ApplyMode: ApplyRuntimeRestart},
		Field{Path: "telegram.allowed_chat_ids", Kind: KindStringList, ApplyMode: ApplyRuntimeRestart},
		Field{Path: "telegram.poll_timeout", Kind: KindDuration, ApplyMode: ApplyRuntimeRestart},
		Field{Path: "slack.base_url", Kind: KindString, ApplyMode: ApplyRuntimeRestart},
		Field{Path: "slack.bot_token", Kind: KindString, Sensitive: true, ApplyMode: ApplyRuntimeRestart},
		Field{Path: "slack.app_token", Kind: KindString, Sensitive: true, ApplyMode: ApplyRuntimeRestart},
		Field{Path: "slack.allowed_team_ids", Kind: KindStringList, ApplyMode: ApplyRuntimeRestart},
		Field{Path: "slack.allowed_channel_ids", Kind: KindStringList, ApplyMode: ApplyRuntimeRestart},
		Field{Path: "line.base_url", Kind: KindString, ApplyMode: ApplyRuntimeRestart},
		Field{Path: "line.channel_access_token", Kind: KindString, Sensitive: true, ApplyMode: ApplyRuntimeRestart},
		Field{Path: "line.channel_secret", Kind: KindString, Sensitive: true, ApplyMode: ApplyRuntimeRestart},
		Field{Path: "line.webhook_listen", Kind: KindString, ApplyMode: ApplyProcessRestart},
		Field{Path: "line.webhook_path", Kind: KindString, ApplyMode: ApplyProcessRestart},
		Field{Path: "line.allowed_group_ids", Kind: KindStringList, ApplyMode: ApplyRuntimeRestart},
		Field{Path: "lark.base_url", Kind: KindString, ApplyMode: ApplyRuntimeRestart},
		Field{Path: "lark.app_id", Kind: KindString, ApplyMode: ApplyRuntimeRestart},
		Field{Path: "lark.app_secret", Kind: KindString, Sensitive: true, ApplyMode: ApplyRuntimeRestart},
		Field{Path: "lark.allowed_chat_ids", Kind: KindStringList, ApplyMode: ApplyRuntimeRestart},
		Field{Path: "mixin.keystore_file", Kind: KindString, ApplyMode: ApplyRuntimeRestart},
		Field{Path: "mixin.allowed_conversation_ids", Kind: KindStringList, ApplyMode: ApplyRuntimeRestart},
		Field{Path: "mixin.task_timeout", Kind: KindDuration, ApplyMode: ApplyRuntimeRestart},
		Field{Path: "mixin.max_concurrency", Kind: KindInt, ApplyMode: ApplyRuntimeRestart, Min: &one},
		Field{Path: "mixin.serve_listen", Kind: KindString, ApplyMode: ApplyProcessRestart},
	)
	return fields
}

func SystemFields() []Field {
	zero := 0.0
	one := 1.0
	return []Field{
		{Path: "logging.level", Kind: KindString, ApplyMode: ApplyProcessRestart, Enum: []string{"", "debug", "info", "warn", "error"}},
		{Path: "logging.format", Kind: KindString, ApplyMode: ApplyProcessRestart, Enum: []string{"text", "json"}},
		{Path: "logging.add_source", Kind: KindBool, ApplyMode: ApplyProcessRestart},
		{Path: "logging.file.dir", Kind: KindString, ApplyMode: ApplyProcessRestart},
		{Path: "logging.file.max_age", Kind: KindDuration, ApplyMode: ApplyProcessRestart},
		{Path: "logging.include_thoughts", Kind: KindBool, ApplyMode: ApplyProcessRestart},
		{Path: "logging.include_tool_params", Kind: KindBool, ApplyMode: ApplyProcessRestart},
		{Path: "logging.include_skill_contents", Kind: KindBool, ApplyMode: ApplyProcessRestart},
		{Path: "logging.max_thought_chars", Kind: KindInt, ApplyMode: ApplyProcessRestart, Min: &zero},
		{Path: "logging.max_json_bytes", Kind: KindInt, ApplyMode: ApplyProcessRestart, Min: &zero},
		{Path: "logging.max_string_value_chars", Kind: KindInt, ApplyMode: ApplyProcessRestart, Min: &zero},
		{Path: "logging.max_skill_content_chars", Kind: KindInt, ApplyMode: ApplyProcessRestart, Min: &zero},
		{Path: "logging.redact_keys", Kind: KindStringList, ApplyMode: ApplyProcessRestart},

		{Path: "workspace_dir", Kind: KindString, ApplyMode: ApplyProcessRestart},
		{Path: "file_state_dir", Kind: KindString, ApplyMode: ApplyProcessRestart},
		{Path: "file_cache_dir", Kind: KindString, ApplyMode: ApplyProcessRestart},
		{Path: "file_cache.max_age", Kind: KindDuration, ApplyMode: ApplyProcessRestart},
		{Path: "file_cache.max_files", Kind: KindInt, ApplyMode: ApplyProcessRestart, Min: &zero},
		{Path: "file_cache.max_total_bytes", Kind: KindInt, ApplyMode: ApplyProcessRestart, Min: &zero},
		{Path: "contacts.dir_name", Kind: KindString, ApplyMode: ApplyProcessRestart},
		{Path: "contacts.proactive.failure_cooldown", Kind: KindDuration, ApplyMode: ApplyRuntimeRestart},
		{Path: "tasks.dir_name", Kind: KindString, ApplyMode: ApplyProcessRestart},
		{Path: "tasks.persistence_targets", Kind: KindStringList, ApplyMode: ApplyRuntimeRestart},
		{Path: "tasks.rotate_max_bytes", Kind: KindInt, ApplyMode: ApplyRuntimeRestart, Min: &zero},
		{Path: "server.max_queue", Kind: KindInt, ApplyMode: ApplyProcessRestart, Min: &one},
		{Path: "bus.max_inflight", Kind: KindInt, ApplyMode: ApplyProcessRestart, Min: &one},
		{Path: "user_agent", Kind: KindString, ApplyMode: ApplyProcessRestart},
		{Path: "auto_update.enabled", Kind: KindBool, ApplyMode: ApplyImmediate},
	}
}
