import {
  PhArrowClockwise,
  PhArrowLeft,
  PhArrowRight,
  PhArrowSquareOut,
  PhArrowUpRight,
  PhBroadcast,
  PhCaretDown,
  PhCaretRight,
  PhCaretUp,
  PhChartBar,
  PhChartLineUp,
  PhCalendarCheck,
  PhChat,
  PhChats,
  PhCheckCircle,
  PhClockCounterClockwise,
  PhCloudArrowDown,
  PhCode,
  PhCompass,
  PhCopy,
  PhCornersOut,
  PhCpu,
  PhCube,
  PhDesktop,
  PhDiceFive,
  PhDotsThree,
  PhFingerprint,
  PhFunnelSimple,
  PhGauge,
  PhGearSix,
  PhGlobe,
  PhGridFour,
  PhInfo,
  PhKeyboard,
  PhLink,
  PhMagicWand,
  PhMagnifyingGlass,
  PhNetwork,
  PhPaperPlaneTilt,
  PhPaperclip,
  PhPencilSimple,
  PhPlus,
  PhPlugsConnected,
  PhProhibit,
  PhPulse,
  PhRobot,
  PhShieldCheck,
  PhSidebarSimple,
  PhSignOut,
  PhSquaresFour,
  PhStop,
  PhTerminalWindow,
  PhTimer,
  PhToolbox,
  PhTrash,
  PhTray,
  PhUserCircle,
  PhUsers,
  PhWallet,
  PhX,
  PhXCircle,
} from "@phosphor-icons/vue";
import { defineComponent, h } from "vue";

const DEFAULT_ICON_SIZE = 24;

function normalizeIcon(component, name) {
  return defineComponent({
    name,
    inheritAttrs: false,
    setup(_props, { attrs, slots }) {
      return () =>
        h(
          component,
          {
            size: DEFAULT_ICON_SIZE,
            weight: "regular",
            focusable: "false",
            "aria-hidden": attrs["aria-label"] ? undefined : "true",
            ...attrs,
          },
          slots,
        );
    },
  });
}

const sources = {
  PhArrowClockwise,
  PhArrowLeft,
  PhArrowRight,
  PhArrowSquareOut,
  PhArrowUpRight,
  PhBroadcast,
  PhCaretDown,
  PhCaretRight,
  PhCaretUp,
  PhChartBar,
  PhChartLineUp,
  PhCalendarCheck,
  PhChat,
  PhChats,
  PhCheckCircle,
  PhClockCounterClockwise,
  PhCloudArrowDown,
  PhCode,
  PhCompass,
  PhCopy,
  PhCornersOut,
  PhCpu,
  PhCube,
  PhDesktop,
  PhDiceFive,
  PhDotsThree,
  PhFingerprint,
  PhFunnelSimple,
  PhGauge,
  PhGearSix,
  PhGlobe,
  PhGridFour,
  PhInfo,
  PhKeyboard,
  PhLink,
  PhMagicWand,
  PhMagnifyingGlass,
  PhNetwork,
  PhPaperPlaneTilt,
  PhPaperclip,
  PhPencilSimple,
  PhPlus,
  PhPlugsConnected,
  PhProhibit,
  PhPulse,
  PhRobot,
  PhShieldCheck,
  PhSidebarSimple,
  PhSignOut,
  PhSquaresFour,
  PhStop,
  PhTerminalWindow,
  PhTimer,
  PhToolbox,
  PhTrash,
  PhTray,
  PhUserCircle,
  PhUsers,
  PhWallet,
  PhX,
  PhXCircle,
};

export const phosphorIcons = Object.fromEntries(
  Object.entries(sources).map(([name, component]) => [name, normalizeIcon(component, name)]),
);
